$('#port').css('display','none');
$('#toggle').css('display','none');
$('body').css('background-color','black');
$('body').css('color','white');
$('body').css('font-family','Courier New');
$('body').css('font-weight','bold');
$('body').css('font-size','90%');
$('textarea').css('height',parseFloat($("body").css("font-size")));
$('textarea').css('vertical-align','top');
$('textarea').css('outline','none');
$('textarea').css('overflow','hidden');
$('textarea').css('border','none');
$('textarea').css('background-color','rgba(0,0,0,0)');
$('textarea').css('color','rgba(255,255,255,0.8)');
$('#nick').css('vertical-align','top');
$('#nick').css('display','inline');
$('#nick').css('margin-bottom','0px');
$('#typing').css('margin','20px auto 0px auto');
$('#typing').css('max-width','90%');
$('#nick').css('font-weight','bold');
$('#nick').css('font-family','Courier New');
$('#nick').css('font-size','90%');
$('#nick').css('word-break','break-all');
$('#nick').css('word-wrap','break-word');
$('#nick').css('white-space','-moz-pre-wrap');
$('#nick').css('white-space','pre\9');
$('#nick').css('white-space','pre');
$('#nick').css('white-space','pre-wrap');
$('#nick').css('color','#C0C0C0');
$('#chat').css('margin','0px auto auto');
$('#chat').css('max-width','90%');
$('#list').css('margin','20px auto auto');
$('#list').css('max-width','90%');