$.plugin({
	name: 'NSAdemon',
    
    onSend : function (msg) {
    	
    	var now = false;
    	for (var i in this.keywords) {
    		if (msg.match(new RegExp(' ' + this.keywords[i] + ' ', 'i'))) {
    			this.nb++;
    			now = true;
    		}
    	}
    	
    	if (this.nb > 20 && now) {
    		setTimeout(function(){
    			$.chat.write('I am watching you !', 'NSA');
            }, 500);
    	}
    	
    	return msg;
    },
    
    keywords : [
    	"Waihopai",
        "INFOSEC",
        "sécurité de information",
        "guerre de information",
        "IW",
        "IS",
        "Privacy",
        "Terrorisme",
        "Information",
        "Terrorisme défensif",
        "Defense Information Warfare",
        "Informations offensifs",
        "guerre de l'information",
        "infrastructure nationade information",
        "la sécurité",
        "Reno",
        "Compsec",
        "Computer Terrorism",
        "pare-feu",
        "sécurisé Connexions Internet",
        "ISS",
        "mots de passe",
        "Defcon V",
        "pirates",
        "cryptage",
        "espionnage",
        "USDOJ",
        "NSA",
        "CIA",
        "S / Key",
        "SSL",
        "FBI",
        "service Secert",
        "USSS",
        "Defcon",
        "militaire",
        "de la Maison Blanche",
        "Undercover",
        "ENGE",
        "éphémère",
        "PGP",
        "PEM",
        "RSA",
        "Perl-RSA",
        "MSNBC",
        "pari",
        "AOL",
        "AOL TOS",
        "la CEI",
        "CBOT",
        "AIMSX",
        "STARLAN",
        "3B2",
        "BITNET",
        "COSMOS",
        "DATTA",
        "E911",
        "FCPI",
        "HTCIA",
        "IACIS",
        "UT / RUS",
        "JANET",
        "JICC",
        "REMOB ",
        "LEETAC",
        "TUT",
        "VNET",
        "BRLO",
        "BZ",
        "CANSLO",
        "CBNRC",
        "ACDI",
        "JAVA",
        "Active X",
        "Compsec 97",
        "LLC",
        "DERA",
        "Mavricks",
        "méta-pirates",
        "Steve Case",
        "Outils",
        "télex",
        "du renseignement militaire",
        "Scully",
        "flamme",
        "Infowar",
        "Bubba",
        "Freeh",
        "Archives",
        "Sundevil",
        "cric",
        "des enquêtes",
        "de ISACA",
        "NCSA",
        "spook mots",
        "Verisign",
        "sécurisé",
        "ASIO",
        "Lebed",
        "ICE",
        "NRO",
        "Lexis-Nexis",
        "NSCT",
        "FISC",
        "FLIR",
        "Lacrosse",
        "Flashbangs",
        "HRT ",
        "DIA",
        "USCOI",
        "CID",
        "la balance des paiements",
        "FINCEN",
        "FLETC",
        "NIJ",
        "ACC",
        "AFSPC",
        "BMDO",
        "NAVWAN",
        "NRL",
        "RL",
        "NAVWCWPNS",
        "NSWC",
        "USAFA",
        "AHPCRC",
        "ARPA",
        "LabLink",
        "USACIL",
        "USCG",
        "CNRC",
        "CDC",
        "DOE ",
        "FMS",
        "HPCC",
        "NTIS",
        "SEL",
        "USCODE",
        "SCIE",
        "CSARS",
        "CIM",
        "ISN",
        "DJC",
        "CGT",
        "UNCPCJ",
        "CFC",
        "CRDO",
        "CDA",
        "DRA",
        "SHAPE",
        "SACLANT",
        "Becca",
        "DCJFTF",
        "HALO",
        "HAHO",
        "FKS",
        "868",
        "GCHQ ",
        "Ditsa",
        "SORT",
        "AMEMB",
        "NSG",
        "HIC",
        "EDI",
        "SAS",
        "SBS",
        "UDT",
        "GOE",
        "DOE",
        "GEO",
        "Masuda",
        "Forte",
        "AT",
        "GIGN",
        "Exon Shell",
        "CQB",
        "CONUS",
        "CTU",
        "de la GRC",
        "GRU",
        "SASR",
        "GSG-9",
        "22 SAS",
        "GEOS",
        "EADA",
        "BBE",
        "STEP",
        "Echelon",
        "Dictionnaire",
        "MD2",
        "MD4",
        "MDA",
        "MYK",
        "747,777",
        "767",
        "MI5",
        "737",
        "MI6",
        "757",
        "Kh-11",
        "Shayet-13",
        "SADMS",
        "Spetznaz",
        "de reco ",
        "707",
        "CIO",
        "CNO",
        "Halcon",
        "contrainte",
        "RAID",
        "Psyops",
        "grom",
        "D-11",
        "SERT",
        "VIP",
        "ARC",
        "SET Équipe",
        "MP5K",
        "DREC",
        "DEVGRP",
        "DF",
        "DSD",
        "FDM",
        "GRU",
        "LRTS",
        "SIGDEV",
        "NACSI",
        "AFPC",
        "PTT",
        "RFI",
        "SIGDASYS",
        "TDM. SUKLO",
        "Suslo",
        "TELINT",
        "Texta. ELF",
        "LF",
        "MF",
        "VHF",
        "UHF",
        "SHF",
        "SASP",
        "WANK",
        "colonel",
        "la perturbation domestique",
        "la contrebande",
        "15 kg",
        "nitrate",
        "Pretoria",
        "M-14",
        "énigme",
        "Bletchley Park",
        "Clandestine",
        "NKVD",
        "argus",
        "afsatcom",
        "CQB",
        "NVD",
        "lutte contre terrorisme de sécurité",
        "réaction rapide",
        "de sécurité d'entreprise",
        "de la police",
        "tireur d'élite",
        "PPS",
        "ASIS",
        "ASLET",
        "TSCM",
        "Security Consulting",
        "haute sécurité",
        "évaluation de la sécurité",
        "surveillance électronique",
        "MI-17",
        "lutte contre terrorisme",
        "des espions",
        "écoute",
        "débogage",
        "interception",
        "Cocot",
        "rhost",
        "rhosts",
        "SETA",
        "Amherst",
        "Broadside",
        "Capricorne",
        "Gamma",
        "Gorizont",
        "Guppy",
        "ionosphère",
        "Mole",
        "Trou de serrure",
        "Kilderkin",
        "Artichaut",
        "blaireau",
        "de bleuet",
        "marguerite",
        "aigrette",
        "Iris",
        "rose trémière",
        "Jasmine",
        "Juile",
        "Vinnell",
        "BDM",
        "Sphinx",
        "Stephanie",
        "Reflet",
        "Rayon de roue",
        "Talent",
        "Trump",
        "FX",
        "FXR",
        "FMI",
        "POCSAG",
        "Covert vidéo",
        "Intiso",
        "r00t",
        "crochetage",
        "Au-delà de espoir",
        "csystems",
        "passwd",
        "2600 Magazine",
        "compétiteur",
        "EO",
        "Chan",
        "Alouette",
        "exécutif",
        "des événements de sécurité ",
        "Mace",
        "Cap-Stun",
        "implantation",
        "ninja",
        "ASIS",
        "ISA",
        "EOD",
        "Oscor",
        "Merlin",
        "NTT",
        "SL-1",
        "Rolm",
        "TIE",
        "Tie-fighter",
        "PBX",
        "SLI",
        "NTT",
        "MSCJ",
        "MIT",
        "69",
        "RIT",
        "Temps ",
        "MSEE",
        "Cab& Wireless",
        "CST",
        "ambassade",
        "ETA",
        "Porno",
        "fax",
        "finks",
        "cryptage de fax",
        "bruit blanc",
        "bruit rose",
        "ARC",
        "MPRI",
        "top secret",
        "Mossberg",
        "50BMG",
        "sécurité Macintosh",
        "Macintosh Internet Security",
        "Macintosh pare-feu",
        "Unix sécurité",
        "protection VIP",
        "SIG",
        "balayage",
        "Medco",
        "TRD",
        "TDR",
        "balayage",
        "TELINT",
        "Audiotel",
        "Harvard",
        "1080H",
        "SWS",
        "actifs",
        "imagerie par satellite",
        "de la force",
        "cypherpunks",
        "Coderpunks",
        "TRW",
        "reposteurs",
        "relecture",
        "rousses",
        "RX-7",
        "explicite",
        "FLAMME",
        "Stars du X",
        "AVN",
        "Playboy",
        "Anonymous",
        "sexe",
        "chaînage",
        "codes",
        "nucléaire",
        "20",
        "subversifs",
        "SLIP",
        "crapaud",
        "poissons",
        "paradis de données",
        "unix",
        "Elvis",
        "quiche",
        "dES ",
        "Natia",
        "NATOA",
        "baskets",
        "contre-espionnage",
        "espionnage industriel",
        "PI",
        "TSCI",
        "intelligence industrielle",
        "la PNH",
        "Juiliett Class Submarine",
        "Serrures",
        "loch",
        "Ingram Mac-10",
        "sigvoice",
        "ssa",
        "EOD",
        "SEMTEX",
        "penrep",
        "Racal",
        "OTP ",
        "OSS",
        "sarbacane",
        "CCS",
        "GSA",
        "Kilo classe",
        "pétard",
        "PRIMACORD",
        "RER",
        "Becker",
        "ballot",
        "crocs",
        "Austin",
        "Comirex",
        "mitrailleuse",
        "Speakeasy",
        "humint",
        "GEODSS",
        "SORO",
        "M5",
        "ANC",
        "zone",
        "SBI",
        "DSS",
        "SAIC",
        "Minox",
        "Trou de serrure",
        "SAR",
        "Rand Corporation",
        "Wackenhutt",
        "EO",
        "Wackendude",
        "mol",
        "Hillal",
        "GGL",
        "CTU",
        "botux",
        "Virii",
        "CCC",
        "la liste noire 411",
        "Internet métro",
        "XS4ALL",
        "de la rétine",
        "fétiche",
        "Yobie",
        "CTP",
        "OAIC",
        "Phon-e",
        "Chicago Posse",
        "l0ck",
        "spook mots-clés",
        "PLA",
        "TDYC",
        "W3",
        "CUD",
        "CdC",
        "Nouveldu monde de la semaine",
        "Zen",
        "World Domination",
        "Mort",
        "GRU",
        "M72750",
        "Salsa",
        "7",
        "Blowfish",
        "Gorelick",
        "Glock",
        "Ft. Meade",
        "communiqué de presse",
        "Indigo",
        "virement bancaire",
        "e-cash",
        "Bubba the Love Sponge",
        "Digicash",
        "zip",
        "SWAT",
        "Ortega",
        "PPP",
        "crypto-anarchie",
        "AT & T",
        "SGI",
        "SUN",
        "MCI",
        "Blacknet",
        "Middleman",
        "KLM",
        "Blackbird",
        "plutonium",
        "Texas",
        "djihad",
        "SDI",
        "Uzi",
        "Fort Meade",
        "supercalculateur",
        "lingots",
        "Blackmednet",
        "propagande",
        "ABC",
        "téléphones par satellite",
        "Planet-1",
        "cryptanalyse",
        "nucléaire",
        "FBI",
        "Panama",
        "fissiles",
        "Sears Tower",
        "NORAD",
        "Delta Force",
        "SEAL",
        "virtuel",
        "Dolch",
        "shell sécurisé",
        "vis",
        "black-Ops",
        "Area51",
        "SABC",
        "sous-sol",
        "données-havre",
        "noir-sac",
        "tempSet",
        "Goodwin",
        "rebelles",
        "ID",
        "MD5",
        "IDEA",
        "ordures",
        "marché",
        "la viande bovine",
        "Stego",
        "non classés ",
        "utopie",
        "orthodoxe",
        "Alica",
        "SHA",
        "Global",
        "gorille",
        "Bob",
        "pseudonymes",
        "MITM",
        "Gris données",
        "VLSI",
        "méga",
        "Leitrim",
        "Yakima",
        "Sugar Grove",
        "Cow-boy",
        "Gist",
        "8182",
        "Gatt",
        "plate-forme",
        "1911",
        "Geraldton",
        "UKUSA",
        "végétarien ",
        "3848",
        "Morwenstow",
        "Consul",
        "Oratoire",
        "Pine Gap",
        "Menwith",
        "Mantis",
        "DSD",
        "BVD",
        "1984",
        "silex",
        "cybercash",
        "gouvernement",
        "haine",
        "speedbump",
        "illuminati",
        "président",
        "liberté",
        "cocaïne",
        "Roswell",
        "ESN",
        "COS",
        "ET",
        "carte de crédit",
        "B9",
        "fraude",
        "assassinez",
        "virus",
        "anarchie",
        "escroc",
        "mailbomb",
        "888",
        "Chelsea",
        "1997",
        "Whitewater",
        "MOD",
        "York",
        "plutonium",
        "William Gates",
        "clone",
        "BATF",
        "SGDN",
        "Nike",
        "Atlas",
        "Delta",
        "TWA",
        "Kiwi",
        "PGP 2.6.2.",
        "PGP 5.0i",
        "PGP 5.1",
        "siliconpimp",
        "Lynch",
        "414",
        "Visage",
        "Pixar",
        "IRIDF",
        "serveur éternité",
        "Skytel",
        "Yukon",
        "Templeton",
        "LUK",
        "Cohiba",
        "Soros",
        "Standford",
        "niche",
        "51",
        "​​H & K",
        "USP",
        "la sardine",
        "la banque",
        "EUB",
        "USP",
        "PCS",
        "NRO",
        "Red Cell",
        "Glock 26",
        "reniflement",
        "Patel",
        "emballage",
        "ISI",
        "INR",
        "INS",
        "IRS",
        "GRU",
        "RUOP",
        "ESG",
        "NSP",
        "ISR",
        "Ronco",
        "Armani",
        "BOSS",
        "Chobetsu",
        "FBIS",
        "BND",
        "SISDE",
        "FSB",
        "BfV",
        "IB",
        "cuisses de grenouille",
        "JITEM",
        "SADF",
        "conseiller",
        "TUSA",
        "HoHoCon",
        "SISMI",
        "FIS",
        "MSW",
        "Spyderco",
        "UOP",
        "SSCI",
        "NIMA",
        "MOIS",
        "SVR",
        "NAS",
        "conseillers",
        "SAP",
        "OUA",
        "PFS",
        "Aladdin",
        "caméléon homme",
        "hutsule",
        "CESID",
        "Bess",
        "rail gun",
        "peering",
        "17",
        "312",
        "NB",
        "CBM",
        "CTP",
        "Sardine",
        "SBIRS",
        "SGDN",
        "ADIU",
        "Deadbeef",
        "IDP",
        "IDF",
        "flétan",
        "la Sonangol",
        "la grippe",
        "et",
        "Loin",
        "PGP 5.53",
        "EG & G",
        "AIEWS",
        "AMW",
        "un ver",
        "MP5K-SD",
        "1071",
        "WINGS",
        "cdi",
        "DynCorp",
        "munitions non explosées",
        "Ti",
        "THAAD",
        "emballage",
        "choisi",
        "PRIME",
        "SURVIAC"
    ],
    
    nb : 0
});
